### ISSUE TITLE
Implement tags for transactions

### ISSUE THREAD

**Issue by phil0x2e** [NickvisionApps/Denaro#101]
It would be nice to have the ability to add multiple groups to transactions.

For example a transaction could be in the group "recurring payments" and "donations".
This would really help to organize transactions, which fit more than one group.

**Comment by fsobolev** [comment]
I now imagine groups entry in transaction dialog similar to the labels list here on github... Colored pill buttons, with a group name and small `x` button inside, circular `+` button on the right side of the list that opens a popup with a list of all groups. Yeah, looking at my contributions, it seems like I'm thrilled by colors, haha 🤣  Gonna make a mockup later.

**Comment by RuboGubo** [comment]
Just to throw my two pence in: If we do implement this, then it would make the count up on the side more complicated, as the sum off all the groups would not equal your total money.

**Comment by nlogozzo** [comment]
> Just to throw my two pence in: If we do implement this, then it would make the count up on the side more complicated, as the sum off all the groups would not equal your total money.

Well the Total, income, and expensas of the account is calculated only from the transactions themselves and has nothing to do with groups, hence why they are two separate sections.

**Comment by zothma** [comment]
If we do implement this feature, this will create some other problems: the CSV will be almost impossible to do, unless each transaction is duplicated... It would look like that for a transaction that belongs to two groups **Group1** and **Group2**:

```csv
1;2022-11-27;Test 1;1;0;30;rgb(53,132,228);-1;Group1;Description 1
1;2022-11-27;Test 1;1;0;30;rgb(53,132,228);-1;Group2;Description 2
```

This would ruin the ability to use the CSV in an external tool like Excel. Plus, from what I've seen in many apps, including my banking app, only one group is added to a transaction...

**Comment by fsobolev** [comment]
> the CSV will be almost impossible to do, unless each transaction is duplicated...

Groups in CSV can be comma separated, so the only problem is to mask commas in groups' names and descriptions when exporting. Or it's possible to use another symbol as separator for groups in CSV (maybe `|`?) So your example will look like this:
```
1;2022-11-27;Test 1;1;0;30;rgb(53,132,228);1|2;Group1|Group 2;Description 1|Description 2
```

> Plus, from what I've seen in many apps, including my banking app, only one group is added to a transaction...

Sounds awesome to me, implementing a feature that other apps don't have! 😄

**Comment by kdw2060** [comment]
Came here to make the same suggestion about categories/tags, so thumbs up for this idea.

I'd like to add one more suggestion: make the description an optional field. At the moment it is mandatory, but I feel like categories/tags are quite self-explanatory and most of the time don't need a description (e.g. I have categories like 'insurance', 'groceries', ...).

**Comment by fsobolev** [comment]
> make the description an optional field

#111

**Comment by nlogozzo** [comment]
@fsobolev So how do we feel about doing this next? Do you want to make some mockups of how a tagging system would work (in conjunction with the current grouping system)?

**Comment by fsobolev** [comment]
![Tags mockup](https://user-images.githubusercontent.com/117388856/216973082-6db12c96-8905-4649-99fb-6f24154e5380.png)

This is my old mockup. Tbh I want to change it completely, but basically the idea and functionality can be the same: each transacion can have any number of tags, they're not in any way related or connected to groups. I don't think we have a good place in sidebar to always show tags there, but maybe we can show them somewhere when a user searches transactions, I have a few ideas, will do some mockups later and we'll see what looks best. I think we can make tags immutable, meaning once created they can't be changed, only deleted, this way we'll be able to have tags as comma separated list in `Tags` column in CSV, without Ids or other additional info.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.0-beta3
