### ISSUE TITLE
Better export

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Denaro#245]
Currently it's only possible to export all transactions sorted by ID. The idea is to have 2 export options: "Export All" and "Export Current". The latter will export only transactions that are currently shown in the window, also sorting should be kept. "Export Current" will also have "New Account" as an option for output format - this way a user will be able to split an account (can be useful in case a user imported a file with a lot of transactions). "Export All" should not have this output option because it's useless.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.4.1-beta1
