### ISSUE TITLE
Diagrams / Pie charts

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Denaro#289]
A pie chart that shows expenses for each group.
        A line chart that shows expenses for each month.
        A heat map that shows expenses for every day of the year.

_Originally posted by @vanillajonathan in https://github.com/nlogozzo/NickvisionMoney/discussions/116_
 
#3 was linked in the discussion as an issue to track progress for this feature, but in result only PDF export was added and that issue was closed.

**Comment by Donkey-Doug** [comment]
Just wanted to say thay icicle diagrams make sense for this type of visualization. Python has plotly icicle charts.

**Comment by nlogozzo** [comment]
Thought i'd share some progress:
![image](https://github.com/NickvisionApps/Denaro/assets/17648453/c6657c34-012d-490e-bb6f-19e4445ac0ad)
![image](https://github.com/NickvisionApps/Denaro/assets/17648453/1582de87-918a-4bfc-83c2-54f6e6f1e91b)
![image](https://github.com/NickvisionApps/Denaro/assets/17648453/b2fc0c97-c46c-4e12-8818-e1aa85c8a7f6)

In PDF:
![image](https://github.com/NickvisionApps/Denaro/assets/17648453/248b3d74-648f-4c2d-a77d-dae863c2c73d)
![image](https://github.com/NickvisionApps/Denaro/assets/17648453/470a6b7a-3c0b-4e8e-82e9-06a141d14b7d)

**Comment by vanillajonathan** [comment]
This looks great!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.0-beta2

**Comment by nlogozzo** [comment]
And we have a release! I urge you all to test out the beta and see how it works for you and come back with any feedback :)
