### ISSUE TITLE
Show Amounts Based On Transactions Shown

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Denaro#366]
From @fsobolev :
> What would be nice is if overview (and maybe groups too) would show numbers for filtered transactions. I think this can be considered, it doesn't add any complexity for users to work with, but we need to decide how the app should treat future transactions in this case. @nlogozzo

So basically I think it will show the number of transactions shown in the transactions list (including future transactions if they are shown in the list)

We can add a row underneath the `Expense` row in the overview section to show the `# of Transactions Shown: _` and then we can find a place for each group row to show the number of transactions shown in the list that belong to that group.

**Comment by fsobolev** [comment]
Sorry for my bad English, but I meant completely different thing. By "numbers" I meant total, income and expense. My suggestion was to make these overview value change but counting not everything in an account but what is currently shown in the window.

**Comment by nlogozzo** [comment]
Ah so you want to show amounts based on the transactions shown in the list and not the whole of the account?

**Comment by fsobolev** [comment]
> Ah so you want to show amounts based on the transactions shown in the list and not the whole of the account?

Correct. I think this can be very helpful for users.

Considering this:

> we need to decide how the app should treat future transactions in this case.

Now I believe that we should not count future transactions. It could be possible to calculate amounts with simple future transactions, but not with repeat transactions that have no end date. Calculations with selective future transactions are totally unobvious and the results will be misleading.
Instead, I suggest to add to transactions row a button that will be shown next to amount label only for future transactions. Clicking on that button will open a popover with information that this is a future transactions and its amount is not taken into account when calculating overview amounts. For the icon I suggest to use [mirrored "history-undo"](https://user-images.githubusercontent.com/117388856/225498833-cfb0b3b4-70c2-4ad1-b4ad-f65aa9fa85bf.png). This idea is inspired by some of banking apps that I use that have similar icon for transactions that are in process.

**Comment by rhilliges** [comment]
@nlogozzo , @fsobolev 
I would like to give this issue a try, if you guys are ok with it?

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.6.0-beta2
