### ISSUE TITLE
GNOME - Dragging Tab Down from TabView Bar Should Move/Open Tab to New Window

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Denaro#395]

**Comment by fsobolev** [comment]
Not sure it will work like this, but theoretically we could:
1. Catch a signal when a tab gets moved out of window
2. Look what is an account path for that tab
3. Open a new Denaro instance with this account path

**Comment by nlogozzo** [comment]
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/signal.TabView.create-window.html

**Comment by nlogozzo** [comment]
I've decided to not support this feature. Nautilus doesn't have it implemented either and it'll be more complicated to implement then it is worth.
