### ISSUE TITLE
Consider using hardcoded or different icon for receipt upload

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Denaro#435]
`document-send-symbolic` doesn't look appropriate with Yaru theme

![Снимок экрана от 2023-04-10 02-06-47](https://user-images.githubusercontent.com/117388856/230800996-aaffbfed-9eec-4df3-a140-4faa9dfa7960.png)

**Comment by nlogozzo** [comment]
Probably best to use the hardcoded one as we have done with other icons

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.4.1-beta1
