### ISSUE TITLE
Use non-latin numerals for cultures that have alternative numerals

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Denaro#450]
https://stackoverflow.com/questions/2298153/how-can-i-convert-english-digits-to-arabic-digits - examples how this can be implemented

**EDIT**: [note](https://www.github.com/dotnet/runtime/issues/47749#issuecomment-771815076) about non-ASCII digits formatting

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.4.1-beta1
