### ISSUE TITLE
Support for Monero (XMR)

### ISSUE THREAD

**Issue by gonzoknows** [NickvisionApps/Denaro#466]
Support for custom Monero (XMR) cryptocurrency. If the ability to mark single transactions as crypto that would be great! Instead of changing all the currency to Monero

**Comment by fsobolev** [comment]
If you move money from some account to monero account and pay from it, there's a transfer in Denaro exactly for that. If you don't want to hassle with transfer but to only mark some transactions that money were converted to another currency, there are groups, transaction description and notes. Later there also will be tags (#101), but there already are multiple solutions for your use case, so I think this issue should be closed.

**Comment by nlogozzo** [comment]
Agreed. Denaro won't support changing currency for individual transactions of an account.  

As @fsobolev you can use transfer to transfer transactions from different Denaro accounts that have different currencies.

**Comment by gonzoknows** [comment]
> Agreed. Denaro won't support changing currency for individual transactions of an account.
> 
> As @fsobolev you can use transfer to transfer transactions from different Denaro accounts that have different currencies.

Will there be support for cryptocurrencies per account?

**Comment by fsobolev** [comment]
> Will there be support for cryptocurrencies per account?

You can use custom currency with unlimited decimal digits.

**Comment by gonzoknows** [comment]
> > Will there be support for cryptocurrencies per account?
> 
> You can use custom currency with unlimited decimal digits.

crypto changes in real time
