### ISSUE TITLE
Support for upcoming transaction notifications 

### ISSUE THREAD

**Issue by gonzoknows** [NickvisionApps/Denaro#476]
Support for notifications for upcoming transactions such as phone bills, mortgage, etc. 

Options for 1 day, 1 week, 1 month or even custom would be great.

**Comment by nlogozzo** [comment]
This sounds like a cool feature! 
Maybe we can add a field in account settings called "Reminders" where you choose 1 day, 1 week, etc...
and then create a section in the UI where you will see a list of remainders for upcoming transactions depending on your settings.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.0-rc1
