### ISSUE TITLE
Denaro crashes when uploading a "extras" file through a network drive

### ISSUE THREAD

**Issue by SomeOrdinaryDude** [NickvisionApps/Denaro#498]
Granted I don't have proof it happens for all NAT solutions, but it happens from my personal nextcloud. 

The GNOME error tracker didn't find much useful information. I'm on a fedora linux 38 system. 

![Screenshot from 2023-05-16 22-11-59](https://github.com/NickvisionApps/Denaro/assets/79510944/8eae950b-5cb1-4982-adc9-56a5832eb8e8)

**Comment by nlogozzo** [comment]
Can you run Denaro via the terminal and see what error is printed on crash?

Also, are you running flatpak? If so, could be #480 in which you'll need to use Flatseal to give Denaro access to the drive.

**Comment by SomeOrdinaryDude** [comment]
> 

That seemed to fix it. However, it isn't ideal that the whole thing crashes, maybe it should just give a access error? My problem is solved, but here is the error output it gives from terminal.

```
(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 00:16:46.091: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 00:16:46.091: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
^C
(base) [linuxworkstation@fedora ~]$ flatpak run org.nickvision.money 

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 00:17:04.126: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 00:17:04.126: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
**
Gtk:ERROR:../gtk/gtkfiledialog.c:890:finish_file_op: assertion failed: (g_list_model_get_n_items (files) == 1)
Bail out! Gtk:ERROR:../gtk/gtkfiledialog.c:890:finish_file_op: assertion failed: (g_list_model_get_n_items (files) == 1)

```

**Comment by nlogozzo** [comment]
The access error sounds like a good idea.

FYI @fsobolev
