### ISSUE TITLE
Toggle selection of all groups

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Denaro#503]
From #348:

> Turn the "Reset Groups Filter" into a toggle button that enables/disables all groups. This way I need at most 3 clicks, if I want to see the transactions of one specific group. Right now, I have to disable all other groups one by one.

I don't think the clear groups button should become a toggle, but a new button should be added. Not sure where to place it, but I will think about this.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.6.0-beta2
