### ISSUE TITLE
CSV import always fails, even with CSVs exported from Denaro itself

### ISSUE THREAD

**Issue by trevnels** [NickvisionApps/Denaro#523]
I'm having trouble importing any CSVs (either exported or manually created according to the format in the docs) into any account, blank or otherwise. Every CSV import attempt seems to result in "Imported 0 transactions from file." *Most other CSV-related issues seem to be about wanting to import other CSV formats, but in this case, it seems like Denaro can't read a file that it wrote.*

Running flatpak `2023.5.0`.

Here's the contents of the file that was exported from a test account and doesn't successfully import into a fresh blank one:
```
ID;Date (en_US Format);Description;Type;RepeatInterval;RepeatFrom (-1=None,0=Original,Other=Id Of Source);RepeatEndDate (en_US Format);Amount (en_US Format);RGBA;UseGroupColor (0 for false, 1 for true);Group(Id Starts At 1);GroupName;GroupDescription;GroupRGBA
1;5/26/2023;test;0;0;-1;;12;rgb(53,132,228);0;-1;;;
```
It does seem like the column names in the exported file don't match those in the docs, which lists the following names (without format info in parentheses this time):
`ID;Date;Description;Type;RepeatInterval;RepeatFrom;RepeatEndDate;Amount;RGBA;UseGroupColor;Group;GroupName;GroupDescription;GroupRGBA`
However, manually replacing the original header with this one doesn't seem to have an effect.

Thanks for the great app, by the way - I've been enjoying it so far.

**Comment by nlogozzo** [comment]
> It does seem like the column names in the exported file don't match those in the docs, which lists the following names (without format info in parentheses this time):

This doesn't matter as the header has no effect on the importing as it skips over it. It must be reading/writing too many `;`, let me look into it...

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.6.0-beta2
