### ISSUE TITLE
Autocomplete transaction description

### ISSUE THREAD

**Issue by cassiogomes00** [NickvisionApps/Denaro#524]
It would be helpful to have an auto-complete feature for transaction descriptions based on existing transactions when you start typing. These suggestions would be based on previous transactions with similar descriptions.

Additionally, it would be nice if these transactions could also display the group to which previous transactions with these descriptions belong. This group can be assigned when selecting a suggestion.

**Comment by nlogozzo** [comment]
Sounds like a cool feature! Thanks :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.6.0-beta2
