### ISSUE TITLE
Flatpak - Can't Open From App Grid

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Denaro#530]
With V2023.5.0 update, Denaro installed from flatpak seems to not be able to be opened from the app grid.
Snap is unaffected
Workaround: Run from terminal (`flatpak run org.nickvision.money`)

**Comment by JPF3N998** [comment]
Can confirm! Thanks for reporting this issue :)

Running Manjaro with GNOME.

Haven't tried Snap but trying to open Denaro from applications menu fails. Both installed via `flatpak in CLI` and `Add/Remove Software`

**Comment by fsobolev** [comment]
There was a flatpak update published with temporary fix, another solution will come to the next version so the issue is still opened.

**Comment by JPF3N998** [comment]
Thanks for the update Fyodor!

**Comment by fsobolev** [comment]
Fixed with #533

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.6.0
