### ISSUE TITLE
Program crashes when mass importing transactions

### ISSUE THREAD

**Issue by NotYourAlejandro** [NickvisionApps/Denaro#546]
### Description
I encountered a program crash while attempting to mass import transactions in the application from a csv file. My csv file contains 1030 transactions. The data is sourced from my bank and was manipulated by myself to allow the application to read it successfully.
From my testing, the program's memory usage starts at 153 MiB, then maxes out during the import at 339 MiB.

### Logs
`Process terminated. A callback was made on a garbage collected delegate of type 'NickvisionMoney.GNOME!NickvisionMoney.GNOME.Views.AccountView+GSourceFunc::Invoke'.`

`app-flatpak-org.nickvision.money-60024.scope: Consumed 58.645s CPU time.`

### Steps to Reproduce:
1. Obtain or create a large csv file that is compatible with Denaro.
2. Launch the application.
3. Select an account (preferably an empty one for testing).
4. On the left-hand panel, click `Actions`, then `Import from File`.
5. Choose the large csv file.

### Expected Behavior
The application should import the transactions within the csv file, then displays the results of the import.

### Actual Behavior
The application imports the transactions within the csv file, but crashes when it finishes, failing to display the results. The imported contents exist on next run.

### Software Versions and Hardware
OS: Fedora 38
DE: KDE Plasma 5.27.5
Kernel: 6.2.15
CPU: AMD Ryzen 5 3600X
GPU: NVIDIA GeForce GTX 1080
Memory: 16 GB (7 GB used during testing)

### Attachments
[https://youtu.be/dmZ2ne93Ksc](https://youtu.be/dmZ2ne93Ksc)

**Comment by nlogozzo** [comment]
> Process terminated. A callback was made on a garbage collected delegate of type 'NickvisionMoney.GNOME!NickvisionMoney.GNOME.Views.AccountView+GSourceFunc::Invoke'.

@fsobolev I thought we were done with these errors 😅

**Comment by fsobolev** [comment]
> > Process terminated. A callback was made on a garbage collected delegate of type 'NickvisionMoney.GNOME!NickvisionMoney.GNOME.Views.AccountView+GSourceFunc::Invoke'.
> 
> @fsobolev I thought we were done with these errors sweat_smile

We were done in TC, but Denaro still has weird callbacks :(

**Comment by fsobolev** [comment]
> I can't seem to find them...it looks ok to me. Do you know where they are? I'll fix them

I think the problem is with dynamic callbacks in `CreateGroupRow` etc, where they are recreated each time:

```
private IGroupRowControl CreateGroupRow(Group group, int? index)
    {
        var row = new GroupRow(group, _controller.CultureForNumberString, _controller.UseNativeDigits, _controller.IsFilterActive(group.Id == 0 ? -1 : (int)group.Id), _controller.GroupDefaultColor);
        row.EditTriggered += EditGroup;
        row.FilterChanged += UpdateGroupFilter;
        if (index != null)
        {
            _rowCallbacks[0] = (x) =>
            {
                try
                {
                    _groupsList.Insert(row, index.Value);
                }
...
```

I remember we had issues with similar callbacks in TC that required access to data outside of callback (`row` in this case), and we changed them so we added Handle to data and passed a pointer to callback.

**Comment by nlogozzo** [comment]
> we changed them so we added Handle to data and passed a pointer to callback

Ok I'll try to attempt that...

**Comment by nlogozzo** [comment]
Got it fixed! Here's importing 511 transactions into a new account:

[Screencast from 2023-06-15 22-35-32.webm](https://github.com/NickvisionApps/Denaro/assets/17648453/57969136-38f4-49db-9bad-36dbd94debe0)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.6.0
