### ISSUE TITLE
The Microsoft Store is asking me to redeem a code

### ISSUE THREAD

**Issue by williamd1k0** [NickvisionApps/Denaro#588]
![image](https://github.com/NickvisionApps/Denaro/assets/10428035/2cc41916-f104-4c44-950d-16a40a91410d)
---
>Note: I'm not a Windows user, I just wanted to try it out so I could recommend it to my friends who use Windows.

**Comment by nlogozzo** [comment]
Support for Windows has been dropped, see https://nickvision.org/posts/0523/removingSupportForWindows.html

Therefore, the app is no longer available on Windows (it has been unlisted from the Microsoft Store, thus it is asking you for a code)

We hope to bring back Windows support in the future. If you friend is a little bit tech-savy, you can tell them to setup WSL on Windows and install Denaro from flatpak and they can run it through that.

**Comment by ieris19** [comment]
@nlogozzo the link you posted on the comment that closed this thread is dead. Google is also not returning any hits and nickvision.org and the denaro docs and the developer blog there are not working either as of today. If anyone is here like me, looking for Windows support, and wishes to read the article, I have found a Markdown version: https://github.com/NickvisionApps/nickvisionapps.github.io/blob/ac9bbe16ebb861cca211b15626b2ae63f20bb9f9/_posts/2023-05-23-removing-windows-support.md
