### ISSUE TITLE
Feature request: Import/export homebank

### ISSUE THREAD

**Issue by wrenix** [NickvisionApps/Denaro#640]
http://homebank.free.fr/en/

**Comment by fsobolev** [comment]
> what file formats does homebank export to that we could use?

According to [features list](http://homebank.free.fr/en/features.php) it exports to QIF so there's already a way to move data from Homebank to Denaro.

**Comment by nlogozzo** [comment]
So then @wrenix I'd recommend using that. If there are any issues importing QIF from Homebank please let us know.

**Comment by wrenix** [comment]
i lost all accounts and categories associations on v2023.6.2
