### ISSUE TITLE
Option to have a space between the symbol and amount

### ISSUE THREAD

**Issue by julianfairfax** [NickvisionApps/Denaro#644]
When using a 3 character currency "symbols" (just letters), Denaro doesn't put a space in-between this symbol and the amount. So, for example, you would see USD1 rather than the correct USD 1. For this reason, Denaro should allow 4 characters as a symbol, or add an option to have a space between the symbol and amount.

**Comment by fsobolev** [comment]
@nlogozzo The problem is different cultures specify different formats for displaying amount with currency symbol (see [CurrencyPositivePattern](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.currencypositivepattern?view=net-7.0#system-globalization-numberformatinfo-currencypositivepattern) [CurrencyNegativePattern](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.currencynegativepattern?view=net-7.0#system-globalization-numberformatinfo-currencynegativepattern)), and I think enforcing `$ n` format is not preferred for all use-cases.

**Comment by nlogozzo** [comment]
I was just thinking of adding a switch to custom currency "show space between symbol and amount", but I think it's best to just look at `CurrencyPositivePattern` and follow that...prevents modification to database table too

**Comment by nlogozzo** [comment]
On further discussion, we will implement a way to change this in custom currency

**Comment by JoseBritto** [comment]
> On further discussion, we will implement a way to change this in custom currency

So something like this?

![image](https://github.com/NickvisionApps/Denaro/assets/64070234/a94e631f-a3c4-4759-8e85-a35e689f8a39)

**Comment by nlogozzo** [comment]
Kind of...we were thinking of just having `Amount Format Style` which is basically a combination of positive and negative and use it for both

**Comment by nlogozzo** [comment]
@JoseBritto would you like to take a shot at implementing it?

**Comment by JoseBritto** [comment]
I was gonna ask you, but this being due for the next release, I think I'm gonna pass. Maybe can I have a shot at implementing the currency conversion tool? I assume that gonna need to integrate with some api  as well.

**Comment by nlogozzo** [comment]
> but this being due for the next release, I think I'm gonna pass

Ok no worries :) Yeah i'm going to get it done now, so I can release an RC1 tonight and stable for Friday.

> Maybe can I have a shot at implementing the currency conversion tool? I assume that gonna need to integrate with some api as well.

Yes feel free to tackle it! I'd like to get it into a release next month but being a big feature I'm ok with it taking some time. And yes it will need some API to pull conversion data from...I don't have any specific one in mind so feel free to choose what you think it best.

If you have any questions, you know how to reach me :)

**Comment by JoseBritto** [comment]
Ok thanks :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.1-rc1

*should be on flathub beta soon...whenever gnome gitlab is up again*

**Comment by nlogozzo** [comment]
> > https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.1-rc1
> > 
> > _should be on flathub beta soon...whenever gnome gitlab is up again_
> 
> I got the new update from Flathub. When trying to actually use the new setting, Denaro irrecoverably freezes.

Could you run the app via terminal `flatpak run org.nickvision.money` and set it again and see if any error message occurs

**Comment by julianfairfax** [comment]
> I mean those gtk-critical messages can be ignored...was the format correctly displayed when you reopened the account? If so, how many transactions do you have in the account?

This issue occurs even when creating a brand new account. Like, if you select the option to use a custom currency during the account creation process, it's an issue.

**Comment by nlogozzo** [comment]
> This issue occurs even when creating a brand new account. Like, if you select the option to use a custom currency during the account creation process, it's an issue.

idk how we didn't see this as I swear it was working no problem in tested...anyway fixed with https://github.com/NickvisionApps/Denaro/commit/f4a705d81c4f11de8a969116bfc7456e5daceb61****
