### ISSUE TITLE
Transactions default color

### ISSUE THREAD

**Issue by n1729m** [NickvisionApps/Denaro#650]
In transaction window, Group color defaults to **Use unique color**. 

Is it possible to have an option to use **Use group color** by default.

![Screenshot_20230819_073319](https://github.com/NickvisionApps/Denaro/assets/96682069/681448c8-f0e2-46bd-9809-9ed98aade25b)

**Comment by nlogozzo** [comment]
Yes I don't know why this wasn't default.

@fsobolev any reason why we didn't do this?

**Comment by fsobolev** [comment]
> @fsobolev any reason why we didn't do this?

New transaction is ungrouped by default, and when changing a group we don't change to group color because if there was some unique color set we want to keep it.

**Comment by nlogozzo** [comment]
> we don't change to group color because if there was some unique color set we want to keep it.

So maybe we can compare the unique color. If it's the default color, change it to group else keep it?

**Comment by fsobolev** [comment]
> So maybe we can compare the unique color. If it's the default color, change it to group else keep it?

That could work.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.1-rc1

*should be on flathub beta soon...whenever gnome gitlab is up again*
