### ISSUE TITLE
Dates in graph sometimes overlap

### ISSUE THREAD

**Issue by alexander-g2** [NickvisionApps/Denaro#675]
![Bildschirmfoto vom 2023-08-28 18-30-29](https://github.com/NickvisionApps/Denaro/assets/60253802/96872e50-9a88-40ac-b22c-438f390f5a4b)
![Bildschirmfoto vom 2023-08-28 18-34-42](https://github.com/NickvisionApps/Denaro/assets/60253802/b16ef516-7372-4e5a-9961-5f88fab2c915)

**Comment by nlogozzo** [comment]
Yeah I've noticed that with some specific width and then if you resize just a little it goes away...have to see which values of the graph width cause this and maybe round up or smth to prevent it..

**Comment by nlogozzo** [comment]
yeah all the date resizing is handled by the graphing library itself...all we do is give it the width of the window so like I said problem have to find the sweet spot of curving the width...will able then to PDFs too.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.1-rc1
