### ISSUE TITLE
Not all recurring transactions are created at the same time

### ISSUE THREAD

**Issue by Hyperspeed1313** [NickvisionApps/Denaro#681]
When I set up a new recurring transaction, only two new transactions will appear: the start date transaction and the first recurrence. Each time I re-open the account, it adds a single further recurring transaction in the series until the recurrences have caught up to present day.

This is a very annoying problem if I'm adding a bunch of data at once as I have to close and re-open the account repeatedly to get it to populate.

**Comment by nlogozzo** [comment]
Hmm interesting....I think this might have broke when we introduced the transaction reminders system. Will look into it

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.0
