### ISSUE TITLE
Opening account settings in “actions” crashes Denaro

### ISSUE THREAD

**Issue by gonzoknows** [NickvisionApps/Denaro#686]

**Comment by fsobolev** [comment]
Please run the app in terminal and provide the output of when it crashes.

Flatpak:
```
flatpak run org.nickvision.money
```

Snap:
```
denaro
```

**Comment by gonzoknows** [comment]
> Please run the app in terminal and provide the output of when it crashes.
> 
> Flatpak:
> 
> ```
> flatpak run org.nickvision.money
> ```
> 
> Snap:
> 
> ```
> denaro
> ```

`(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:23.526: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:23.527: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.794: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.794: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.796: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.796: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.796: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.797: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.812: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.812: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.814: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.814: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.814: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.814: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.827: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.827: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.829: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.829: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.829: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.829: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.843: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.843: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.845: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.845: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.845: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.845: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.860: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.860: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.862: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.862: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.862: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.862: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.876: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.876: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.878: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.878: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.878: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.878: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.894: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.894: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.896: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.896: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.896: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.896: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.911: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.911: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.913: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.913: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.913: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.913: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.927: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.927: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.928: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.929: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.929: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.929: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.943: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.943: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.945: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.945: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.945: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.945: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.960: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.960: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.962: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.962: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.962: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.962: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.977: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.977: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.978: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.979: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.979: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.979: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.995: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.995: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.997: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.997: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.997: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:26.997: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:27.012: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:27.012: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:27.013: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:27.013: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:27.014: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 09:45:27.014: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
UnhandledException - unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GLib.Internal.StringArrayNullTerminatedSafeHandle..ctor(String[] array)
   at Gtk.StringList.New(String[] strings)
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog..ctor(Builder builder, AccountSettingsDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 290
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog..ctor(AccountSettingsDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 335
   at NickvisionMoney.GNOME.Views.AccountView.AccountSettings(SimpleAction sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 849
   at GObject.Signal`2.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
`

**Comment by gonzoknows** [comment]
> Seems like a duplicate of #680 Are you sure you're running latest stable version (2023.9.0)?

yes

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.1-rc1
