### ISSUE TITLE
Increase the number of digits after the delimiter

### ISSUE THREAD

**Issue by UrtsiSantsi** [NickvisionApps/Denaro#699]
Currently if the rate is smaller than 1/250 it shows 0.00

![image](https://github.com/NickvisionApps/Denaro/assets/142679804/cde37fb5-3a0c-4a9f-922b-07bf8b0ead02)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.2-beta1
