### ISSUE TITLE
Currency converter source and result fields overlap if window is small

### ISSUE THREAD

**Issue by JoseBritto** [NickvisionApps/Denaro#706]
![image](https://github.com/NickvisionApps/Denaro/assets/64070234/c1098804-83e8-49a8-a0b2-cf2174f65761)
![image](https://github.com/NickvisionApps/Denaro/assets/64070234/7aa962ff-8927-4449-ab59-2a0fff30a0f0)

Happens when running from main branch and not in the latest stable release

**Comment by fsobolev** [comment]
Only happens with GTK 4.12
Gonna change the design then...

**Comment by JoseBritto** [comment]
Here is a screencast incase it helps in anyway

[screencast](https://github.com/NickvisionApps/Denaro/assets/64070234/69c31eb6-c7b1-4a48-9509-14f8efc6a8ab)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.2-beta1
