### ISSUE TITLE
Strange order of transactions

### ISSUE THREAD

**Issue by UrtsiSantsi** [NickvisionApps/Denaro#749]
![image](https://github.com/NickvisionApps/Denaro/assets/142679804/9320d8f3-03d5-4385-a236-126e90743939)

Delete some transactions and create new ones, all with the same date. The new transactions will be placed in the positions of the deleted ones, until the count of deleted transactions is reached. After that they will appear at the end of the list. Restarting the app will show the correct order. 
In the screenshot above I first deleted 2 and created 5, then deleted 1 and create 6 and 7. The order is unrelated to the name or amount.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2024.1.0
