### ISSUE TITLE
Inconsistent transaction numbers

### ISSUE THREAD

**Issue by UrtsiSantsi** [NickvisionApps/Denaro#750]
If you delete a few transactions and then create new ones, the new ones will have higher number then the last created. For example if the last transaction is 5 and I delete 3,4, and 5 and create a new one, the new one will have number 6. It is the same if I delete all transactions and don't close the app. But if I delete all transactions and restart the app, the new transactions will start from 1.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2024.1.0
