### ISSUE TITLE
Tags should be ellipsezed 

### ISSUE THREAD

**Issue by UrtsiSantsi** [NickvisionApps/Denaro#751]
Otherwise if they are too long they can push everything to the right and completely hide the transactions.

**Comment by nlogozzo** [comment]
Do you have proof of this?

The sidebar has a max-width set, so it shouldn't grow past '320' px or something like that

**Comment by nlogozzo** [comment]
It was the `can-shrink` property on `Gtk.Button` needed to be set to `true` :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2024.1.0
