### ISSUE TITLE
Tags toggled stated not very clear

### ISSUE THREAD

**Issue by UrtsiSantsi** [NickvisionApps/Denaro#752]
Currently it is not easy to distinguish if tags are all toggled or all untoggled. A better interface will be using check marks, similar to groups and overview.

**Comment by nlogozzo** [comment]
Tags can be very numerous compared to groups which would cause super long scrolling of the sidebar for no reason. I think the current design is the best for a tags interface. They are toggle buttons that clearly show toggled and untoggled. If you believe that they buttons don't show "toggle-ness" clear enough that's a GTK design problem.
