### ISSUE TITLE
QIF import : missing description

### ISSUE THREAD

**Issue by squalou** [NickvisionApps/Denaro#755]
Hi,

I'm running flatpak version 2023.11.0

I've just tested this app, and to begin Iimported a QIF file.
(I made sure dates where in MM/DD/YYYY format ;) )

```
!Type:Bank
D12/04/2023
T-42.94
PSOME DESCRIPTION 02/12 FOR SOMETHING
^
D12/04/2023
T-45.76
PSOME OTHER DESCRIPTION 02/12 
^
```

import runs fine BUT all description fields are empty (`N/A`)

What may be wrong ?

**Comment by JoseBritto** [comment]
Closing this now. If I got something wrong, please feel free to reopen
