### ISSUE TITLE
Help Documents not found

### ISSUE THREAD

**Issue by edent** [NickvisionApps/Denaro#759]
I tried to import a CSV. It said there were no transactions found. I clicked help on the pop-up. I got this error.

![Document Not Found. The URI ‘help:tagger/import-export’ does not point to a valid page. Search for packages containing this document.](https://github.com/NickvisionApps/Denaro/assets/837136/2eb4be0e-7b9d-4e2f-94a9-f0333778fac2)

I'm using the latest Flatpak version.

```
org.nickvision.money
2023.11.0
GTK 4.12.4
libadwaita 1.4.2
Flatpak
en-GB
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

**Comment by nlogozzo** [comment]
Denaro isn't translated for en-GB, hence no docs are installed for it.

You can go to the website and access the en-US docs: https://nickvision.org/denaro.html

*Might be a good instead to check if a docs language exists and if not open the english website instead.*

**Comment by edent** [comment]
Thanks - let me know if you want help translating the docs :-)

**Comment by nlogozzo** [comment]
> Thanks - let me know if you want help translating the docs :-)
> 

Feel free to head over to https://hosted.weblate.org/engage/nickvision-money/ and add in the translation when you have time :)

**Comment by nlogozzo** [comment]
For the next update tho i will definitely make it fallback to the en-US docs if none are available...

**Comment by edent** [comment]
The translation site says:

> Select a valid choice. en_GB is not one of the available choices.
> This list includes only basic languages. Please contact project maintainers to add others.

Fallback to en-US is fine. But I am happy to check for any tweaks in en-GB if you want.

**Comment by nlogozzo** [comment]
> Please contact project maintainers to add others.

I'll look into adding that.

**Comment by JoseBritto** [comment]
The URI shown is for tagger. This has to be updated

https://github.com/NickvisionApps/Denaro/blob/e7922dcd880fb8f1d8dc3c77b8b10e2c5c03e21d/NickvisionMoney.Shared/Helpers/DocumentationHelpers.cs#L24

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2024.1.0
