### ISSUE TITLE
Nothing to import from the file

### ISSUE THREAD

**Issue by bennypowers** [NickvisionApps/Denaro#762]
I've generated .ofx exports from [toshl finance](https://toshl.com). Here's a redacted minimal repro:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?OFX OFXHEADER="200" VERSION="220" SECURITY="NONE" OLDFILEUID="NONE" NEWFILEUID="NONE"?>
<OFX>
    <BANKMSGSRSV1>
        <STMTTRNRS>
            <CURDEF>ILS</CURDEF>
            <BANKACCTFROM>
                <BANKID>000</BANKID>
                <ACCTID>000</ACCTID>
                <ACCTTYPE>CHECKING</ACCTTYPE>
            </BANKACCTFROM>
            <BANKTRANLIST>
                <DTSTART>20130615000000.000[+0000]</DTSTART>
                <DTEND>20231220000000.000[+0000]</DTEND>
                <STMTTRN>
                    <TRNTYPE>OTHER</TRNTYPE>
                    <DTPOSTED>20130501000000.000[+0000]</DTPOSTED>
                    <TRNAMT>-47.00</TRNAMT>
                    <FITID>17100-0</FITID>
                    <MEMO>Kupat Holim</MEMO>
                    <SIC>🏥 Health &amp; Personal Care;Health Insurance 💳, insurance</SIC>
                </STMTTRN>
            </BANKTRANLIST>
        </STMTTRNRS>
    </BANKMSGSRSV1>
</OFX>
```
If I remove the emoji and hebrew glyphs, and the tags from the `<SIC>` tag (the `;` and everything to the right), it's the same result. Same thing if I change the `<CURDEF>` to `USD`

**Comment by JoseBritto** [comment]
I'm not sure what is there to be signed into here but the exception is thrown is this:
  
```
 OfxSharp.OFXParseException: Sign On information not found
   at OfxSharp.OFXDocumentParser.Parse(String ofxString)
   at OfxSharp.OFXDocumentParser.ParseOfxDocument(String ofxString)
   at OfxSharp.OFXDocumentParser.Import(String ofx)
   at NickvisionMoney.Shared.Models.Account.ImportFromOFXAsync(String path, String defaultTransactionRGBA) 
  
  NickvisionMoney.Shared/Models/Account.cs:line 1428
  ```
  At this line:
 https://github.com/NickvisionApps/Denaro/blob/0b68871e86cce8de1b080d18f8de159e92c05a81/NickvisionMoney.Shared/Models/Account.cs#L1428

**Comment by JoseBritto** [comment]
We're not logging the error to the terminal here. Need to fix that as well.

**Comment by JoseBritto** [comment]
@bennypowers If possible can you try #763 and see if that is the actual exception being thrown?

**Comment by bennypowers** [comment]
![image](https://github.com/NickvisionApps/Denaro/assets/1466420/1484a639-f2e0-4747-b66f-301ba1183f42)
I used Builder's "Run Project" button to get this screenshot

**Comment by JoseBritto** [comment]
Its the same error. Thanks. Just wanted to confirm that the error isn't caused due to trimming the file.

**Comment by nlogozzo** [comment]
Your account is also missing the `LEDGERBAL` section...I've added a dummy one too as it's not used by Denaro but required as per the ofx spec.

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/Denaro/assets/17648453/c34ddc0d-ba28-4be9-bf34-b96a923f8511)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2024.1.0

**Comment by bennypowers** [comment]
Thank you! I was able to import transactions from Toshl.

However, we've noted that Toshl's ofx exports don't always fit the spec. It also appears from a cursory search of the spec PDF that there's no standard way to assign taxonomy like categories(groups) or tags. The transactions I imported did not retain their taxonomy in Money.

Toshl stores category and tag in the `<SIC>` tag in this format: `Category;TagA,TagB,TagC`. It seems to me the correct way to address this is to transform the .ofx file myself before importing. Is there documentation available for Denaro's expected format for things like categories, tags, notes, receipts, etc?

**Comment by nlogozzo** [comment]
As you said yourself,  there's no specification in the OFX standard for a standard way of storing groups/categories,  tags, etc... 

Therefore, when reading OFX files, Denaro will only import transactions. 

You could use a CSV file to import more types of data, however that requires a specific format to the CSV which can be found here on Denaro's docs: https://htmlpreview.github.io/?https://raw.githubusercontent.com/NickvisionApps/Denaro/main/NickvisionMoney.Shared/Docs/html/C/import-export.html
