### ISSUE TITLE
GNOME World

### ISSUE THREAD

**Issue by julianfairfax** [NickvisionApps/Denaro#766]
In addition to joining Circle, it would also be nice if the app's code were moved to [GNOME World](https://gitlab.gnome.org/World). GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by nlogozzo** [comment]
See: https://github.com/NickvisionApps/Tagger/issues/421#issuecomment-1874631288
