### ISSUE TITLE
Feature request: opening balance

### ISSUE THREAD

**Issue by necdetaliozdur** [NickvisionApps/Denaro#768]
As far as I can see, an option to set an opening balance is missing.

I have several checking/savings accounts that I want to track, but all of them already have a nonzero balance in them. I can treat the opening balance as a one-time income, but that feels like an ugly workaround in otherwise a gorgeous-looking expense tracker.

**Comment by nlogozzo** [comment]
If we were to implement an opening balance, we'd probably also create a one time income transaction in the case the user types in a wrong amount and needs to change the amount.
