### ISSUE TITLE
Feature request: currency drop-down menu

### ISSUE THREAD

**Issue by necdetaliozdur** [NickvisionApps/Denaro#769]
It would be nice to have a list of all available currencies when opening an account with a currency different from the system locale. Currently, this can only be achieved by manually entering information about the foreign currency, which feels a bit cumbersome.

**Comment by nlogozzo** [comment]
I don't believe it's best to list every currency available for the user to chose to use for an account. That is why we designed the custom currency feature the way we did. 

This prevents the user from having to scroll through a list of hundreds of currencies just to find the one they need and also always users to use non-real currency, i.e. currency from games or whatever they may choose as you can define your own.
