### ISSUE TITLE
Tutorial on using the app

### ISSUE THREAD

**Issue by 2zqa** [NickvisionApps/Denaro#770]
I recently started using this app and I think it has great potential to help me with keeping my finances in order. However, I am not aware on how to use the app to its full potential. Perhaps it is a good idea to recommend some articles or reading material to the user upon installation and/or in the help section (F1), so they don't get discouraged or lost.

**Comment by nlogozzo** [comment]
Most of the app's features and capabilities are documented right within the app...accessible from the main menu --> documentation.

I don't really know of a more clearer place to place it then there.

If you find features missing from the documentation don't hesitate to ask us to provide more clearer docs.

**Comment by 2zqa** [comment]
Apologies, I should have been more clear. The documentation on how to use app itself is great and understandable. What I was trying to say is: perhaps it is useful for users to be presented with some links to articles on how to create a budget, what good financial hygiene is, and how I can use Denaro to become more financially responsible.

**Comment by nlogozzo** [comment]
I mean if you have any links in mind I'd be more than happy to consider them, however, I am not even close to being financially literate so I wouldn't be including any links/offering financial advice. I think it's best, from Denaro's point of view, to clearly document and explain the app's features and capabilities, and have a user explore financial plans and strategies on their own and adapt Denaro to their needs and plans.

**Comment by 2zqa** [comment]
I am also looking for them, hence the issue... :smiley:

Maybe if other people stumble upon this issue, they could offer some articles that have worked for them and that integrate well with Denaro. Or they could write their own article, describing how Denaro can be used with their financial advice.

I also realize that giving "financial advice" probably requires legal disclaimers, so that might further complicate this issue.
