### ISSUE TITLE
Use Payees in QIF Importing

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Denaro#775]
### Discussed in https://github.com/NickvisionApps/Denaro/discussions/774

<div type='discussions-op-text'>

<sup>Originally posted by **terminalmage** January 27, 2024</sup>
I have QIF exports which contain transactions with both payee and memo fields. However, denaro's ledger format doesn't appear to support payees at all. Every one of my transactions has a payee, but many do not have have a memo field. For example, interest earned/charged doesn't really need a memo field, the transaction category gives you all the info you need to know about that transaction.

Unfortunately this means that after importing, a lot of my transactions simply say "N/A" due to a lack of a memo field.</div>

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2024.2.0

**Comment by terminalmage** [comment]
Tested and this works great, thanks!
