### ISSUE TITLE
Crash when select current month

### ISSUE THREAD

**Issue by cassiogomes00** [NickvisionApps/Denaro#779]
# Descriprion

Sometimes, click on the "Select Current Month" button makes the app crash with the following exception:

```
UnhandledException - unhandled exception: System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateOnly..ctor(Int32 year, Int32 month, Int32 day)
   at NickvisionMoney.GNOME.Views.AccountView.OnDateRangeEndYearChanged() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 1318
   at NickvisionMoney.GNOME.Views.AccountView.<.ctor>b__70_28(Object sender, NotifySignalArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 252
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

# How to reproduce

- Open an account
- Mess arround with viewing/filtering options (can't tell exactly with action(s) trigger the error)
- Click on the "Select Current Month" button

# Expected behaviour

Filter transaction by the month selected in the calendar widget

# System Info

## Hardware Information:

- **Hardware Model:** ASUS TUF GAMING B550M-PLUS WIFI II
- **Memory:** 32,0 GiB
- **Processor:** AMD Ryzen™ 5 5600 × 12
- **Graphics:** AMD Radeon™ RX 550 / 550 Series
- **Disk Capacity:** 1,0 TB

## Software Information:

- **Firmware Version:** 3002
- **OS Name:** Arch Linux
- **OS Build:** rolling
- **OS Type:** 64-bit
- **GNOME Version:** 45.3
- **Windowing System:** Wayland
- **Kernel Version:** Linux 6.7.1-arch1-1
- **Formats**: Brasil

## App Information
- **Version**: 2024.1.0
- **Package**: Flatpak
- **Source**: Flathub

**Comment by JoseBritto** [comment]
Thanks for reporting this bug.

Reproducing consistently:
1. Click show current month when on February 2024
2. Change end year from 2024 Feb 29 to 2023 Feb 29 (impossible date)
3. Crash!

**Comment by cassiogomes00** [comment]
I found another way to reproduce it consistently:

1. Click "Select Current Month"
2. Click "Reset To Today"
3. Click "Select Current Month"
4. Crash

**Comment by JoseBritto** [comment]
Seems like that one too is the same bug.  It's not happening on #780 branch. If possible would you be able to confirm the pr fixes it?

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2024.2.0

*Will be available through Flathub in 20 minutes*
